ports:
    - port: 5173
      onOpen: open-preview
      visibility: private
      name: Website
      description: Preview of Website

tasks:
    - name: Installing Dependencies & Start Dev Server
      init: npm install
      command: |
          npm run dev
